### ISSUE TITLE
the cards in the docs/card are overflowing on top of one another at 100% zoom level view of screen

### ISSUE THREAD

**Issue by ganeshkondaka** [arihantcodes/spectrum-ui#38]
the cards in the docs/card are overflowing on top of one another at 100% zoom level view , but they are perfect at 90% zoom level
 
**100% zoom level view is the default view for any pc**

https://github.com/user-attachments/assets/5c502eb4-b50a-49c7-b3be-a6059c9e3119

expected behaviour :
they should align perfectly at the 100% zoom level

**Comment by ganeshkondaka** [comment]
assign me , 
i can fix this issue

**Comment by Harsha-10** [comment]
@ganeshkondaka Mine is 14 inch screen and it's having much more alignment issues. fix the alignment for 14 inch too

**Comment by ganeshkondaka** [comment]
but @arihantcodes wants contributers to add more components rather than solving these minor issues , i guess .
and yeah that is also true , we can solve these issues later aswell .
