### ISSUE TITLE
[bug] : increase padding of components in light mode

### ISSUE THREAD

**Issue by harshal050** [arihantcodes/spectrum-ui#8]
#issue : 8
![Screenshot 2024-12-15 020554](https://github.com/user-attachments/assets/85b6e5ec-b1f7-4916-b7c7-86217833f0e5)

increase some padding of components in light mode

**Comment by manishkumar123456** [comment]
please  explane me that how to setup this project  and dependicieses

**Comment by manishkumar123456** [comment]
how i setup this project locally in my machine  please explane me
